security:
  password_min_length: 12
  max_login_attempts: 3
  lockout_duration: 300
  session_timeout: 1800
  mfa_code_expiry: 300
  rate_limit:
    max_requests: 5
    window: 60

database:
  path: "data/secure_users.json"
  backup_enabled: true
  backup_interval: "daily"

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  use_tls: true

logging:
  level: "INFO"
  audit_log: "logs/security_audit.log"
  system_log: "logs/system.log"
  max_file_size: "10MB"
  backup_count: 5

monitoring:
  enabled: true
  metrics_interval: 60
  health_check_interval: 30

server:
  host: "0.0.0.0"
  port: 5001
  debug: false
  ssl_enabled: false