security:
  # Authentication
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: true
    max_age_days: 90
    history_count: 12
  
  # Multi-Factor Authentication
  mfa:
    totp_enabled: true
    email_2fa_enabled: true
    biometric_enabled: true
    backup_codes: 10
    
  # Session Management
  session:
    timeout_minutes: 30
    max_concurrent: 3
    jwt_expiry_hours: 1
    refresh_token_days: 7
    
  # Rate Limiting
  rate_limits:
    login_attempts: 5
    window_minutes: 15
    global_requests: 1000
    per_ip_requests: 100
    
  # IP Security
  ip_security:
    geolocation_check: true
    vpn_detection: true
    tor_blocking: true
    reputation_check: true
    whitelist: []
    blacklist: []
    
  # Device Security
  device_security:
    fingerprinting: true
    new_device_notification: true
    trusted_devices_max: 5
    device_registration_required: false
    
  # Threat Detection
  threat_detection:
    brute_force_protection: true
    anomaly_detection: true
    honeypot_endpoints: ['/admin', '/wp-admin', '/.env']
    suspicious_patterns: ['../../../', 'union select', '<script>']
    
  # Encryption
  encryption:
    algorithm: 'AES-256-GCM'
    key_rotation_days: 30
    data_at_rest: true
    data_in_transit: true
    
  # Audit & Compliance
  audit:
    log_all_events: true
    retention_days: 365
    real_time_alerts: true
    compliance_mode: 'SOC2'
    
  # Headers & CSRF
  headers:
    hsts_max_age: 31536000
    csp_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'"
    csrf_protection: true
    
  # Backup & Recovery
  backup:
    encryption: true
    frequency: 'daily'
    retention_count: 30
    offsite_backup: false